# Author: Gonzalo Ramos Zúñiga
# Since: 2022/12/28

AWSTemplateFormatVersion: 2010-09-09
Resources:
  PortfolioBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption: # Enable & Amazon S3-managed keys (SSE-S3) selected
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: s3-react-portfolio
      ObjectLockEnabled: false
      OwnershipControls: # ACLs disabled (recommended) selected
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration: # Block all public access unticked
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  PortfolioBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PortfolioBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref PortfolioBucket, "/*"]]
  PorfolioDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          Compress: true
          SmoothStreaming: false
          TargetOriginId: PortfolioBucketOriginId
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig: # S3 bucket with static website hosting selected
              OriginProtocolPolicy: http-only
            DomainName:
              !Select [1, !Split ["//", !GetAtt PortfolioBucket.WebsiteURL]]
            Id: PortfolioBucketOriginId
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
        PriceClass: PriceClass_All # Use all edge locations (best performance)